In [2]:
import numpy as np
from scipy.linalg import expm

def skew_symmetric(v):

    return np.array([[0, -v[2], v[1]],
                     [v[2], 0, -v[0]],
                     [-v[1], v[0], 0]])

def screw_to_transform(S, theta):

    omega = S[:3]
    v = S[3:]
    omega_hat = skew_symmetric(omega)
    R = expm(omega_hat * theta)
    p = (np.eye(3) - R).dot(np.cross(omega, v)) + np.outer(omega, omega) @ v * theta
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = p
    return T

d1 = 0.2
d2 = 0.3
L = 1.2
S1 = np.array([0, 0, 1, 0, 0, 0])
S2 = np.array([0, 1, 0, -d1, 0, 0])
S3 = np.array([0, 1, 0, -d1 - d2, 0, 0])
S4 = np.array([1, 0, 0, 0, -d1 - d2, 0])
S5 = np.array([0, 1, 0, -d1 - d2, 0, 0])
S6 = np.array([0, 0, 1, 0, 0, 0])


theta = [np.pi/6, -np.pi/4, np.pi/3, -np.pi/6, np.pi/4, -np.pi/3]


M = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, L],
    [0, 0, 0, 1]
])


T = np.eye(4)
for S, angle in zip([S1, S2, S3, S4, S5, S6], theta):
    T = T @ screw_to_transform(S, angle)

T_end_effector = T @ M
print("Transformation matrix of the end-effector relative to the base:")
print(T_end_effector)


Transformation matrix of the end-effector relative to the base:
[[ 0.7875689   0.27394008  0.55198918 -0.07734889]
 [-0.61544643  0.30460599  0.72693939  0.81846667]
 [ 0.03099863 -0.91223463  0.40849365  0.56866807]
 [ 0.          0.          0.          1.        ]]
